### ISSUE TITLE
Height on main wrapper not correct

### ISSUE THREAD

**Issue by JordanSayner** [giotiskl/Filterizr#11]
Hi,

I am using this plugin in two instances on a site I'm developing. In both instances it is working out the height on the main wrapper wrong.

First off, i will mention the height on main wrapper issue.

both instances i am missing a few pixels form the main wrappers height that is auto generated bu the script. on instance i am using the "sameSize" layout, this is missing 20px ish. and the other instance, i am using the "vertical" layout, which is missing about 2 pixels

The vertical layout has a border at the bottom of each item, which is getting cut off on when the filter is set to all. When the filter is set to one of my categories, the border shows fine. There isn't any images within items, just plain text.

``` javascript
                var filterizd = $('.m-client-list').filterizr('setOptions', {
                    layout: 'vertical'
                });
```

and the css 

``` css
.m-client-list {
  border-top: 2px solid #646469; }
  .m-client-list-item {
    border-bottom: 2px solid #646469;
    margin-right: 0;
    opacity: 0; }
    .m-client-list-item-content p {
      font-weight: 300;
      font-size: 12px;
      margin: 0;
      padding: 10px 0; }
    .m-client-list-item-title h3 {
      margin: 0;
      padding: 10px 0; }
    .m-client-list-item:after {
      content: "";
      display: block;
      clear: both; }
```

I'm hoping the problem with the 20 pixels that are missing with be fixed with the issue above. The 20 pixels missing is using the layout "sameSize"
